# Generated by Django 3.0.2 on 2020-01-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_rooms', '0002_auto_20200107_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
